# Generated by Django 3.1.2 on 2022-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippets',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
