# Generated by Django 3.1.2 on 2022-08-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_auto_20220809_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
